version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # Password for root access
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PORT: '3306'
      MYSQL_ROOT_HOST: '%' # Allow root access from any host
    secrets:
      - db_root_password
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  app:
    image: payroll-app:latest
    restart: always
    environment:
      DB_IP: db
    depends_on:
      - db
    ports:
      - '3000:3000'
    expose:
      # Opens port 3306 on the container
      - '3000'

secrets:
  db_root_password:
    file: database/db_root_password.secret
# Names our volume
volumes:
  my-db: